### ISSUE TITLE
Config Json

### ISSUE THREAD

**Issue by samsonrosen** [tattn/homebridge-rm-mini3#4]
Hey! Very excited about this code.

I've got this setup and homebridge recognises my RM Mini 3.

I am only interested in using the RM Mini 3 to power on/off my AMP & TV.

How would I write my JSON code to work with two different devices?

Also, do you have any references to capturing the IR codes or what format they need to be in? I have a Mac with an Infrared port.

Thanks in advance!

Sam

**Comment by tattn** [comment]
> How would I write my JSON code to work with two different devices?

I intended to be able to send multiple commands, but it did not actually work...
I will think about ways to make it possible.
